### ISSUE TITLE
ViewModels and ABP in demo

### ISSUE THREAD

**Issue by papyr** [lprichar/LeesStore#14]
Lee, I was watching your videos on YT, very nice I gave you a TU.

Can you explain what happens with a view model and where does it belong, for e.g. do I put it in the DTO object?

thanks

**Comment by lprichar** [comment]
Sorry @papyr I didn't see this until just now.  ViewModels's are typically associated with an MVVM design pattern.  That pattern is generally more applicable to UI's with live 2-way databinding like Xamarin or UWP.  The ABP architecture generally just has models and DTO's.  Anything you might use a ViewModel for with ABP'd you'd use a DTO.  Does that help?
